from domain.entity import Entity
from domain.position import Position

class Satellite(Entity):

    def __init__(self, 
                 mission_name, 
                 position, 
                 sensor):

        super().__init__(position)      # Initializes the parent class and calls the parent class constructor
        self.mission_name = mission_name
        self.sensor = sensor
        self.angular_speed = (0.0001,   # latitude per step
                              0.0010,   # longitude per step
                              0         # altitude
                             )
        self.last_observations = []     # last_observations contains observations generated by this satellite during the last simulation step


    def update(self, context):

        self.update_position()

        self.last_observations = self.operate_sensor(context["entities"])


    def __str__(self):
        return (
                f'Satellite #{self.id} '
                f'({self.mission_name}) '
                f'at {self.position}'
                )


    def update_position(self):
        new_position = Position(
                                latitude=self.position.latitude + self.angular_speed[0],
                                longitude=self.position.longitude + self.angular_speed[1],
                                altitude=self.position.altitude + self.angular_speed[2]
                                )

        self.position = new_position


    def operate_sensor(self, entities):            # entities is the list of entities
        return self.sensor.scan(
                                observer_position = self.position,
                                entities = entities
                                )


    def get_observations(self):
        return self.last_observations
    